### ISSUE TITLE
Fix log parsing for Safari

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-benderjs-runner#10]
There is some issue with JSON parsing. See https://travis-ci.org/github/ckeditor/ckeditor4-benderjs-runner-tests/builds/750367960#L251.

**Comment by Comandeer** [comment]
It seems like a very tricky one. We got intermixed data streams from both server and Bender instances, e.g.

```json
{"test collapsed in text - h offset 0 - createBookmark2":{"result":"pass","message":"Test passed","type":"test","name":"test collapsed in text - h offset 0 - createBookmark2","d
{"level":30,"time":1624280824816,"pid":10228,"hostname":"Tomaszs-MBP","reqId":86,"res":{"statusCode":200},"responseTime":0.3874859996140003,"msg":"request completed"}
uration":1}
```

The easiest fix would be to disable logs from Fastify server.

**Comment by Comandeer** [comment]
I've just discovered yet another issue with JSON parsing: some very long messages can be incorrectly divided into several data chunks, resulting in incorrect JSON to parse.
