### ISSUE TITLE
Integrate with CI

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-benderjs-runner#2]
As mentioned in [README](https://github.com/ckeditor/ckeditor4-benderjs-runner#2-integrate-with-gh-actionsworkflows):

> There are [Linux, macOS and Windows images available](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) so I assume at least Chrome, Firefox, Edge, Safari and IE11 can be covered here. For IE8-IE10 and mobiles (so Chrome@Android and Safari@iOS) we will need integration with BrowserStack (or similar service).
> 
> Since GH Actions allows matrix runs it will be easier to define - I'm not only sure if such steps run simultaneously (that would be faster) or one after another.

We can try with forked `ckeditor/ckeditor4` repo. I guess the workflow could be triggered on `commit` and `pullrequest` events in `ckeditor4` repo, checkout `ckeditor4-benderjs-runner` and try to run tests.

**Comment by f1ames** [comment]
It seems it won't work out-of-the-box due to missing graphical environment. And there is no straightforward docs on setting-up `xvfb` there (for sure it's doable). Some tests where done in #1.

We decided to check how it works on Travis CI and it was straightforward to set up (see #2) so for now we will go with Travis CI.

**Comment by f1ames** [comment]
Blocked by #1.

**Comment by Comandeer** [comment]
Closed in [`2e93c54`](https://github.com/ckeditor/ckeditor4/commit/2e93c542fd6e84a0297768d8755ba393ed9e3611).
