### ISSUE TITLE
Changes in dependencies should trigger full run

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4-benderjs-runner#26]
Right now - changes in package.json produce an empty test query.

Due to the nature of such changes - it should be rather a full run. I know that our deps are only the 'dev' one - but still - passed full run indicates that nothing breaks. Also, invalid changes should be visible at least at installing deps level.

**Comment by sculpt0r** [comment]
Related: https://github.com/ckeditor/ckeditor4/issues/5183

Probably any changes that end up with an empty test filter should at least run `core` or a full run. Or we should declare what is allowed to not run test, like changes in the README or CHANGELOG

**Comment by jacekbogdanski** [comment]
Should be fixed by https://github.com/ckeditor/ckeditor4/issues/5183
